# Generated by Django 4.2.13 on 2025-10-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventlog',
            new_name='analytics_e_event_t_b30595_idx',
            old_name='analytics_e_event_t_0a8e64_idx',
        ),
    ]
