# Generated by Codex CLI
from __future__ import annotations

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(  # PersonalityItem
            name="PersonalityItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=8, unique=True)),
                ("text_ja", models.TextField()),
                (
                    "trait",
                    models.CharField(
                        choices=[("O", "O"), ("C", "C"), ("E", "E"), ("A", "A"), ("N", "N")],
                        max_length=1,
                    ),
                ),
                ("is_reversed", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(unique=True)),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(  # SurveyResult
            name="SurveyResult",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_scores",
                    models.JSONField(
                        help_text="Keyed by item code (E1, A1, ...) with the original 1-5 answers"
                    ),
                ),
                ("sum_O", models.PositiveSmallIntegerField()),
                ("sum_C", models.PositiveSmallIntegerField()),
                ("sum_E", models.PositiveSmallIntegerField()),
                ("sum_A", models.PositiveSmallIntegerField()),
                ("sum_N", models.PositiveSmallIntegerField()),
                ("scaled_O", models.PositiveSmallIntegerField()),
                ("scaled_C", models.PositiveSmallIntegerField()),
                ("scaled_E", models.PositiveSmallIntegerField()),
                ("scaled_A", models.PositiveSmallIntegerField()),
                ("scaled_N", models.PositiveSmallIntegerField()),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
